name: CI Application Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cicd/task1

    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: setup python
      uses: actions/setup-python@v7
      with:
        python-version: '3.13'

    - name: install linters
      run: pip install ruff

    - name: Run ruff
      run: ruff check .

